import type { Template } from "@timothycrooker/ai-context-core";

const MANIFEST_SCHEMA = JSON.stringify(
	{
		$schema: "https://json-schema.org/draft/2020-12/schema",
		title: "ai-context manifest",
		type: "object",
		additionalProperties: false,
		required: ["version", "modulesDir", "scopesFile", "targets"],
		properties: {
			$schema: { type: "string" },
			version: { const: 1 },
			modulesDir: { type: "string", minLength: 1 },
			scopesFile: { type: "string", minLength: 1 },
			claudeOutput: { type: "string", minLength: 1 },
			targets: {
				type: "object",
				minProperties: 1,
				required: ["root"],
				additionalProperties: {
					type: "string",
					minLength: 1,
				},
			},
		},
	},
	null,
	2,
);

const SCOPES_SCHEMA = JSON.stringify(
	{
		$schema: "https://json-schema.org/draft/2020-12/schema",
		title: "ai-context scopes",
		type: "object",
		additionalProperties: false,
		required: ["version", "scopes"],
		properties: {
			$schema: { type: "string" },
			version: { const: 1 },
			claudeRulesDir: { type: "string", minLength: 1 },
			scopes: {
				type: "array",
				minItems: 1,
				items: {
					type: "object",
					additionalProperties: false,
					required: ["id"],
					properties: {
						id: { type: "string", minLength: 1 },
						codexTarget: { type: "string", minLength: 1 },
						includes: {
							type: "array",
							minItems: 1,
							items: { type: "string", minLength: 1 },
						},
						codexIncludes: {
							type: "array",
							minItems: 1,
							items: { type: "string", minLength: 1 },
						},
						claudeIncludes: {
							type: "array",
							minItems: 1,
							items: { type: "string", minLength: 1 },
						},
						codexAgents: {
							type: "array",
							minItems: 1,
							items: { type: "string", minLength: 1 },
						},
						claudeMemories: {
							type: "array",
							minItems: 1,
							items: { type: "string", minLength: 1 },
						},
						claudeRuleFile: { type: "string", minLength: 1 },
						claudePaths: {
							type: "array",
							minItems: 1,
							items: { type: "string", minLength: 1 },
						},
						parity: { type: "boolean" },
						reason: { type: "string", minLength: 1 },
					},
				},
			},
		},
	},
	null,
	2,
);

export const MONOREPO_TEMPLATE: Template = {
	name: "monorepo",
	files: [
		{
			path: ".ai/context/schemas/manifest.schema.json",
			content: MANIFEST_SCHEMA,
		},
		{
			path: ".ai/context/schemas/scopes.schema.json",
			content: SCOPES_SCHEMA,
		},
		{
			path: ".ai/context/manifest.json",
			content: JSON.stringify(
				{
					$schema: "./schemas/manifest.schema.json",
					version: 1,
					modulesDir: ".ai/context/modules",
					scopesFile: ".ai/context/scopes.json",
					claudeOutput: "CLAUDE.md",
					targets: {
						root: "AGENTS.md",
						api: "apps/api/AGENTS.md",
						web: "apps/web/AGENTS.md",
					},
				},
				null,
				2,
			),
		},
		{
			path: ".ai/context/scopes.json",
			content: JSON.stringify(
				{
					$schema: "./schemas/scopes.schema.json",
					version: 1,
					claudeRulesDir: ".claude/rules",
					scopes: [
						{
							id: "api",
							codexTarget: "api",
							codexIncludes: [
								".ai/rules/backend-core.md",
								".ai/rules/security-core.md",
							],
							claudeIncludes: [
								".ai/rules/backend-core.md",
								".ai/rules/security-core.md",
							],
							codexAgents: ["apps/api/AGENTS.md"],
							claudeMemories: ["apps/api/CLAUDE.md"],
						},
						{
							id: "web",
							codexTarget: "web",
							codexIncludes: [
								".ai/rules/frontend-core.md",
								".ai/rules/ui-core.md",
							],
							claudeIncludes: [
								".ai/rules/frontend-core.md",
								".ai/rules/ui-core.md",
							],
							codexAgents: ["apps/web/AGENTS.md"],
							claudeMemories: ["apps/web/CLAUDE.md"],
						},
					],
				},
				null,
				2,
			),
		},
		{
			path: ".ai/context/modules/010-project-overview.md",
			content: [
				"---",
				"id: project-overview",
				"targets:",
				"  - root",
				"order: 10",
				"---",
				"# Project Overview",
				"",
				"Describe your project, its purpose, and high-level architecture here.",
				"Keep this module lean — push domain-specific rules into `.ai/rules/` files.",
				"See the [content guide](docs/content-guide.md) for writing effective context.",
			].join("\n"),
		},
		{
			path: ".ai/context/modules/020-product-context.md",
			content: [
				"---",
				"id: product-context",
				"targets:",
				"  - root",
				"order: 20",
				"---",
				"## Product Context",
				"",
				"Describe your product boundaries, user-facing behavior, and domain concepts.",
				"This context is shared across all scopes — keep it high-level.",
			].join("\n"),
		},
		{
			path: ".ai/rules/backend-core.md",
			content: [
				"# Backend Core Rules",
				"",
				"Conventions for the API layer and backend services.",
				"",
				"**Key files**: `apps/api/src/routes/`, `apps/api/src/services/`",
				"",
				"## Conventions",
				"",
				"- Keep route handlers thin — extract business logic into service files",
				"- Use Zod schemas for all request and response validation",
				"- Name service files `<entity>.service.ts`",
				"- Return typed error responses, never throw raw HTTP status codes",
				"",
				"## Verification",
				"",
				"- `pnpm --filter api test` — must pass after any route or service change",
				"- `pnpm typecheck` — zero errors required",
				"- Check for N+1 queries when adding new database joins",
				"",
				"## Gotchas",
				"",
				"- The auth middleware sets `req.tenantId` from the JWT — never read tenant from the request body",
				"- `DELETE` endpoints use soft-delete by default — pass `{ hard: true }` only for GDPR purges",
				"- Rate limiting is per-IP in development but per-tenant in production — test both configurations",
			].join("\n"),
		},
		{
			path: ".ai/rules/frontend-core.md",
			content: [
				"# Frontend Core Rules",
				"",
				"Conventions for the web application and client-side code.",
				"",
				"**Key files**: `apps/web/src/components/`, `apps/web/src/hooks/`, `apps/web/src/pages/`",
				"",
				"## Conventions",
				"",
				"- Use the shared API client from `lib/api.ts` — never call `fetch` directly",
				"- Keep component files under 200 lines; split into subcomponents when needed",
				"- Co-locate hooks with the components that use them",
				"- Prefer server-side data fetching over client-side `useEffect` calls",
				"",
				"## Verification",
				"",
				"- `pnpm --filter web test` — must pass after any component or hook change",
				"- Check responsive behavior at 375px, 768px, and 1280px breakpoints",
				"",
				"## Gotchas",
				"",
				"- The router uses file-based routing — component file names become URL paths",
				"- State accessed in `useEffect` must be in the dependency array or it silently stales",
				"- SSR hydration mismatches cause layout flicker — avoid `typeof window` checks in render",
			].join("\n"),
		},
		{
			path: ".ai/rules/security-core.md",
			content: [
				"# Security Core Rules",
				"",
				"Security constraints that apply across the entire codebase.",
				"",
				"**Key files**: `apps/api/src/middleware/auth.ts`, `apps/api/src/middleware/rate-limit.ts`",
				"",
				"## Conventions",
				"",
				"- All API endpoints require authentication unless explicitly allowlisted",
				"- Use parameterized queries for all database access — never interpolate user input",
				"- Sanitize HTML output to prevent XSS — use the shared `sanitize()` helper",
				"- Log security events (failed auth, permission denied) to the audit logger",
				"",
				"## Verification",
				"",
				"- Review all new endpoints for auth middleware usage",
				"- Run `pnpm audit` after adding or updating dependencies",
				"- Check that no secrets appear in client-side bundles",
				"",
				"## Gotchas",
				"",
				"- Tenant identifiers must come from the auth middleware — never trust body or query params",
				"- The `admin` role bypasses row-level security — test admin and non-admin paths separately",
				"- CORS is configured per-environment — the dev config allows `localhost:*` which production must not",
			].join("\n"),
		},
		{
			path: ".ai/rules/ui-core.md",
			content: [
				"# UI Core Rules",
				"",
				"Design system and visual consistency rules.",
				"",
				"**Key files**: `apps/web/src/components/ui/`, `apps/web/src/styles/`",
				"",
				"## Conventions",
				"",
				"- Use shared UI primitives from `components/ui/` — never create one-off styled elements",
				"- Follow the spacing scale: 4px, 8px, 12px, 16px, 24px, 32px, 48px",
				"- Use semantic color tokens (`--color-primary`, `--color-danger`) not raw hex values",
				"- All interactive elements must have visible focus indicators for accessibility",
				"",
				"## Verification",
				"",
				"- Visual review at light and dark theme variants",
				"- Run accessibility linter on new components",
				"- Check that touch targets are at least 44x44px on mobile",
				"",
				"## Gotchas",
				"",
				"- The design system uses CSS custom properties — Tailwind `@apply` does not resolve them",
				"- Icon components are tree-shaken — import individual icons, not the barrel export",
				"- Z-index values above 50 conflict with the modal overlay — use the `z-index` scale in `tokens.css`",
			].join("\n"),
		},
		{
			path: ".codex/config.toml",
			content: [
				'project_root_markers = [".git"]',
				"project_doc_max_bytes = 65536",
				"",
				"[features]",
				"child_agents_md = true",
			].join("\n"),
		},
		{
			path: ".gitignore",
			content: [
				"node_modules",
				"dist",
				".DS_Store",
				"CLAUDE.local.md",
				".ai/secrets.local.env",
			].join("\n"),
		},
	],
};
