import process from "node:process";
import { execFileSync } from "node:child_process";
import {
  formatContextError,
  loadManifest,
  loadMcpRegistry,
} from "@timothycrooker/ai-context-core";
import type { McpServer } from "@timothycrooker/ai-context-core";

interface InstallOptions {
  user?: boolean;
  dryRun?: boolean;
}

// Build the `claude mcp add ...` argv for a user-scope server.
function claudeAddArgs(s: McpServer): string[] {
  const t = s.transport;
  if (t.type === "stdio") {
    const env = Object.entries(s.env ?? {}).flatMap(([k, v]) => ["-e", `${k}=${v}`]);
    return ["mcp", "add", s.name, "-s", "user", ...env, "--", t.command, ...(t.args ?? [])];
  }
  const transportFlag = t.type === "sse" ? "sse" : "http";
  return ["mcp", "add", s.name, t.url, "-t", transportFlag, "-s", "user"];
}

export function runMcpInstall(name: string, opts: InstallOptions): void {
  try {
    const cwd = process.cwd();
    const manifest = loadManifest(cwd);
    const reg = loadMcpRegistry(cwd, manifest);
    const server = reg?.servers.find((s) => s.name === name);
    if (!server) {
      console.error(`MCP server '${name}' not found in registry.`);
      process.exit(1);
      return;
    }
    if (!opts.user) {
      console.error(
        "Only --user install is supported. Project-scope servers are generated by `ai-context build`."
      );
      process.exit(1);
      return;
    }

    for (const target of server.targets) {
      if (target !== "claude") {
        console.log(`note: automated user-install is not implemented for '${target}'; configure '${name}' manually.`);
        continue;
      }
      const args = claudeAddArgs(server);
      console.log(`claude ${args.join(" ")}`);
      if (!opts.dryRun) {
        execFileSync("claude", args, { stdio: "inherit" });
      }
    }

    if (server.auth === "oauth") {
      console.log(`Next: run /mcp in your client to authenticate '${name}'.`);
    }
  } catch (error) {
    console.error(formatContextError(error));
    process.exit(1);
  }
}
